"""Asset table change

Revision ID: 36dd5d13b518
Revises: 6924979226be
Create Date: 2023-07-13 07:33:22.478296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dd5d13b518'
down_revision = '6924979226be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depreciation_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('depreciation_rate')

    # ### end Alembic commands ###
