"""Initial migration

Revision ID: b505cce2ea46
Revises: 9b3f6f336087
Create Date: 2023-07-11 21:43:32.461656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b505cce2ea46'
down_revision = '9b3f6f336087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('asset_category_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'asset_category', ['parent_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asset_category_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('parent_category_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
